apiVersion: v1
kind: Service
metadata:
  name: apt-mirror-nginx
  namespace: infra-apt-mirror
  labels:
    app: apt-mirror-nginx
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30081
    protocol: TCP
  selector:
    app: apt-mirror-nginx
