apiVersion: v1
kind: Namespace
metadata:
  name: k8s-pups-local-llm
---
apiVersion: v1
kind: Namespace
metadata:
  name: user-pods-local-llm
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
